
jobs:
  test:
    executor:
      name: node/default
      tag: '14.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn install
          name: Run YARN tests
      - run:
          command: yarn run test
          name: Run YARN tests
      - run:
          command: yarn run cov:send
          name: Run YARN tests
      - run:
          command: yarn run cov:check
          name: Run YARN tests
      
orbs: 
  node: circleci/node@3.0.1
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test